//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealershipInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSalesForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarSalesForm()
        {
            this.SaleContracts = new HashSet<SaleContract>();
        }
    
        public long CarSaleFormID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int AddOnID { get; set; }
        public long CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public string VIN { get; set; }
        public int BranchID { get; set; }
    
        public virtual VehicleAddOn VehicleAddOn { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContract> SaleContracts { get; set; }
        public virtual DealerBranch DealerBranch { get; set; }
    }
}
