//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealershipInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerBank()
        {
            this.SaleContracts = new HashSet<SaleContract>();
        }
    
        public int BankID { get; set; }
        public double BadCreditRate { get; set; }
        public double FairCreditRate { get; set; }
        public double GoodCreditRate { get; set; }
        public double ExcellentCreditRate { get; set; }
        public byte MaxLoanTerm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleContract> SaleContracts { get; set; }
    }
}
