//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealershipInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleContract
    {
        public int SaleContractID { get; set; }
        public System.DateTime ContractDate { get; set; }
        public string isCashFlag { get; set; }
        public double FinanceRate { get; set; }
        public byte FinanceTerm { get; set; }
        public double DueMonthly { get; set; }
        public int BankID { get; set; }
        public long CarSaleFormID { get; set; }
    
        public virtual CarSalesForm CarSalesForm { get; set; }
        public virtual PartnerBank PartnerBank { get; set; }
    }
}
