//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealershipInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleAddOn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleAddOn()
        {
            this.CarSalesForms = new HashSet<CarSalesForm>();
        }
    
        public int AddOnID { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string ForVehicleType { get; set; }
        public int QuantityAvail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarSalesForm> CarSalesForms { get; set; }
    }
}
